on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
  update-app:
    name: Update app
    runs-on: ubuntu-latest
    steps:
      - name: update the app on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /root/ironfist-bot
            git pull
            yarn
            yarn build
            yarn pm2 restart bot --update-env